### PR TITLE
Add action for creating versions

### PR DESCRIPTION
**Pull request by mjuopperi**

### CODE REVIEW

**Comment by evjere** [comment]
Thanks @mjuopperi for the pr! As a quick glance looks pretty nice. One question regarding the use case is that do you ever release or archive those versions? Should that use case be covered as well?

**Review by evjanne — COMMENTED** [review]
We initially implemented this action to manage Jira issues which makes me think of the naming if we merge the suggested changes. Should we move it to yet another repository with a broader name and a configuration structure that would support more new use cases with the Jira API?

Also, the PR description is going to be used as release notes, so a small description of what was done would be in order.

**Comment by mjuopperi** [comment]
> Thanks @mjuopperi for the pr! As a quick glance looks pretty nice. One question regarding the use case is that do you ever release or archive those versions? Should that use case be covered as well?

Probably yes. Lets see where this feature ends up first :D

**Comment by mjuopperi** [comment]
> We initially implemented this action to manage Jira issues which makes me think of the naming if we merge the suggested changes. Should we move it to yet another repository with a broader name and a configuration structure that would support more new use cases with the Jira API?

Yeah the naming ends up being quite confusing. There is lots of reusable code for other Jira features in this repo, so it would be nice to be able to share the functionality.

**Pull request closed without merging**
